plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "com.tiffinservices.staff"
    compileSdk 35

    defaultConfig {
        applicationId "com.tiffinservices.staff"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    flavorDimensions += "role"
    productFlavors {
        admin {
            dimension "role"
            applicationIdSuffix ".admin"
            versionNameSuffix "-admin"
            resValue "string", "app_name", "Dabba Dope Admin"
        }
        driver {
            dimension "role"
            applicationIdSuffix ".driver"
            versionNameSuffix "-driver"
            resValue "string", "app_name", "Dabba Dope Delivery"
        }
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.15.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
}
